# Generated by Django 6.0.1 on 2026-01-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('daily_rate', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
