# Generated by Django 6.0.1 on 2026-01-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicles',
        ),
    ]
